GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2lkZW9uIiwiaWF0IjoxNjUzMDAwODgyLCJleHAiOjE2NTMwMDA4OTd9.HPrSkZ09-Q1LeDOYLHZbx04XB2j0rS1JTSokdBQvlG0

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Gideon"
}

###


DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2lkZW9uIiwiaWF0IjoxNjUzMDAwODgyLCJleHAiOjE2NTMwMDA4OTd9.HPrSkZ09-Q1LeDOYLHZbx04XB2j0rS1JTSokdBQvlG0"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2lkZW9uIiwiaWF0IjoxNjUzMDAwOTE4fQ.t6l9dcBCv9H1oPJVyIVJdLSPDOYn5E2mfeoYgu7tGsI"
}


