GET http://localhost:3000/users


###

GET http://localhost:3000/users/62835b490436f4da15589000

###

POST http://localhost:3000/users
Content-Type: application/json 

{
    "username": "Mattheus",
    "password": "Test4321"
}

###

DELETE http://localhost:3000/users/62862262e1f4300e7b579227

###

PATCH http://localhost:3000/users/62835b490436f4da15589000
Content-Type: application/json

{
    "username": "Mattheus"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Wouter",
    "password": "Test1234"
}