GET http://localhost:3000/users


###

GET http://localhost:3000/users/62835b490436f4da15589000

###

POST http://localhost:3000/users
Content-Type: application/json 

{
    "username": "Potgieter",
    "password": "Test4321"
}

###

DELETE http://localhost:3000/users/62837f07519be111b92c883a

###

PATCH http://localhost:3000/users/62835b490436f4da15589000
Content-Type: application/json

{
    "username": "Mattheus"
}